### ISSUE TITLE
Relaties per object in /relations

### ISSUE THREAD

**Issue by por** [transparantnederland/api#24]
Via Wouter:

> Zou jij in kunnen bouwen om per object het aantal relaties per object mee te geven? Bijvoorbeeld met de data die ik terug krijg van de onderstaande url, krijg ik 2 objecten terug. "Gemeente Eijsden-Margraten" en "Partij Groot Eijsden-Margraten". Het object "Gemeente Eijsden-Margraten" heeft heel veel relaties. Graag zou ik het aantal relaties meekrijgen. Dit aantal gebruik ik om terug te koppelen aan de gebruiker en waarschijnlijk als middel om het aantal nodes op scherm te verbergen.
> 
> https://api.transparantnederland.nl/relations?id=urn:hgid:overheidsorganisaties/132294

**Comment by por** [comment]
Ik ben niet zeker of ik het goed begrijp. Wil je dat het `/relations` endpoint per object ook het aantal “sub-relaties” meegeeft?

**Comment by WouterEekhout** [comment]
Dat klopt!

**Comment by por** [comment]
Onze database is daar helaas niet voor geoptimaliseerd. Zonder veel extra werk zullen queries dus veel te traag worden. Wel kan je natuurlijk zelf individuele queries doen, om te weten hoeveel sub nodes er zijn per node, vooraleer ze te renderen.

Dat zou betekenen dat je veel extra requests moet doen natuurlijk, maar in principe zou de API dat aan moeten kunnen. Ik weet niet of je dit standaard doet op de client side, of dat je zelf een server hebt draaien die de data transformeert alvorens het naar de client side te sturen. In het laatste geval zou dit geen extra impact moeten hebben op extra geheugengebruik in de browser.
